os: Visual Studio 2015

# Skip build on normal pushes
skip_non_tags: true

artifacts:
  - path: godot\bin\*.exe
    name: GodotBinary

environment:
  PYTHON: C:\Python27
  BUILD_REVISION: official
  ANGLE_SRC_PATH: C:\projects\godot-builds\angle
  matrix:
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: yes
      TARGET: release_debug
      ARCH: amd64
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: yes
      TARGET: release_debug
      ARCH: x86
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: no
      TARGET: release
      ARCH: amd64
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: no
      TARGET: release_debug
      ARCH: amd64
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: no
      TARGET: release
      ARCH: x86
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: no
      TARGET: release_debug
      ARCH: x86
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release
      ARCH: amd64
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release_debug
      ARCH: amd64
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release
      ARCH: x86
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release_debug
      ARCH: x86
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release
      ARCH: amd64_arm
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release_debug
      ARCH: amd64_arm

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install --egg scons  # it will fail on AppVeyor without --egg flag
  - if defined VS call "%VS%" %ARCH%  # if defined - so we can also use mingw
  - git submodule update --init --recursive # download submodules
  - ps: Start-FileDownload https://github.com/GodotBuilder/godot-builds/releases/download/_tools/angle.7z
  - 7z x angle.7z

before_build:
  - echo %BUILD_REVISION%
  - echo %GD_PLATFORM%
  - python --version
  - scons --version
  - cl.exe

build_script:
  - cd godot
  - scons platform=%GD_PLATFORM% target=%TARGET% tools=%TOOLS% warnings=no

deploy:
  description: 'Godot binaries deployed by Travis CI and AppVeyor'
  provider: GitHub
  auth_token:
    secure: DYTTAkQFPIDq2YL6hPMOttlHdJ9ZL6dYdOtGFIEneO8BTYx6keJRvewsdzgP2QGA
  artifact: GodotBinary
  on:
    appveyor_repo_tag: true
